document.getElementById("group7").addEventListener("click",function(){
    window.location.href="./festiveCategory.html";
});
document.getElementById("group8").addEventListener("click",function(){
    window.location.href="./fastFoodCategory.html";
});
document.getElementById("group9").addEventListener("click",function(){
    window.location.href="./mainFoodCategory.html";
});
document.getElementById("group10").addEventListener("click",function(){
    window.location.href="./drinkCategory.html";
});
document.getElementById("group11").addEventListener("click",function(){
    window.location.href="./dessertsCategory.html";
});
document.getElementById("group15").addEventListener("click",function(){
    window.location.href="./breakfastsCategory.html";
});

